[package]
name = "face-validation-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
onnxruntime = "0.0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "face-validation-service"
path = "web/main.rs"
